const steps = [
    {
        "plane": true,
        "toPlane": false,
        "partial": false,
        "centroid": true,
        "forceCount": 32,
        "interp": false,
        "iterative": false,
        "animate": true,
    },
    {
        "plane": false,
        "toPlane": false,
        "partial": false,
        "centroid": false,
        "forceCount": 0,
        "interp": false,
        "iterative": false,
        "animate": false,
    },
    {
        "plane": true,
        "toPlane": false,
        "partial": false,
        "centroid": false,
        "forceCount": 0,
        "interp": false,
        "iterative": false,
        "animate": false,
    },
    {
        "plane": true,
        "toPlane": true,
        "partial": false,
        "centroid": false,
        "forceCount": 0,
        "interp": false,
        "iterative": false,
        "animate": false,
    },
    {
        "plane": false,
        "toPlane": true,
        "partial": true,
        "centroid": false,
        "forceCount": 0,
        "interp": false,
        "iterative": false,
        "animate": false,
    },
    {
        "plane": false,
        "toPlane": false,
        "partial": false,
        "centroid": true,
        "forceCount": 0,
        "interp": false,
        "iterative": false,
        "animate": false,
    },
    {
        "plane": false,
        "toPlane": false,
        "partial": true,
        "centroid": true,
        "forceCount": 1,
        "interp": true,
        "iterative": false,
        "animate": false,
    },
    {
        "plane": false,
        "toPlane": false,
        "partial": true,
        "centroid": true,
        "forceCount": 32,
        "interp": true,
        "iterative": true,
        "animate": false,
    },
    {
        "plane": true,
        "toPlane": false,
        "partial": true,
        "centroid": true,
        "forceCount": 32,
        "interp": false,
        "iterative": false,
        "animate": true,
    },
]